name: 'Create Release'
description: 'A GitHub Action to create a release'
author: 'Volker Schmitz'
inputs:
  repo-token:
    description: 'GitHub token with repo scope'
    required: true
  trigger-release:
    description: 'If set to true, the action will create a release'
    required: false
    default: ${{ github.event.pull_request.merged }}
runs:
  using: 'node12'
  main: 'dist/index.js'
